### ISSUE TITLE
Some code review

### ISSUE THREAD

**Issue by rand00** [AryanGodara/portimpl#1]
Hey @AryanGodara - I have a couple of comments - it would probably be been better if I get commit rights, so I can do a proper code-review - but let's maybe do that next time. Overall I think the code looks good.

* It's always a good idea to print any errors, even when you don't use the result monad - [here you just silently ignore errors](https://github.com/AryanGodara/portimpl/blob/b1d40646a44edcafdf422ce1dc263ee6d60304c2/bin/main.ml#L2)
* It's not so good style to [overwrite existing modules in scope with your own version](https://github.com/AryanGodara/portimpl/blob/b1d40646a44edcafdf422ce1dc263ee6d60304c2/bin/midi.ml#LL1C1-L1C1). Here there is even an indirection into the `Util` module first, so for the reader to know where `Result.Syntax` comes from, they must read that module too. It's better to directly `open Util.Result.Syntax`, and don't `include Result` in there
* It looks like you have [two different shutdown procedures](https://github.com/AryanGodara/portimpl/blob/b1d40646a44edcafdf422ce1dc263ee6d60304c2/bin/midi.ml#L19)? I'm not into how portmidi works, but I guess this could become a single `shutdown`
* You should never run any side-effecting computations [directly in a library module](https://github.com/AryanGodara/portimpl/blob/b1d40646a44edcafdf422ce1dc263ee6d60304c2/bin/midi.ml#L41). Instead this should become an `init` procedure in there, which is then called from `main.ml` on startup
* You should avoid printing to `stdout` from within a library procedure - instead log in the code that uses the library, or use a logging library like `logs` if really needed. `logs` makes it possible to specify log-level, turn off logging, specify where to log, scope the logging etc. This way the user of the library is still in control of logging, even though the library is hooked up to it. (It's fine to print to stdout, if for debugging purposes, and you don't commit the code)

**Comment by AryanGodara** [comment]
@rand00 , sorry for the delay. I've tried to address these issues in the PR opened above
#2
